export const user = {
  profile: {
    name: "Rahul Jadhav",
    contact_number: "9404378965",
    email: "rahul.rj9421@gmail.com",
    about_me:
      "Hi, I'm a computer science enthusiast and B.Tech graduate having around two and half years of experience as a software engineer in the media industry. I’m passionate about programming and delivering, clean, test-covered, well-designed, and scalable code. I seek to learn new technology solutions that make life easier.",
    actions: [
      {
        name: "linkedin",
        link: "https://www.linkedin.com/in/rahul-jadhav-922b0811a/"
      },
      {
        name: "github",
        link: "https://github.com/pain11"
      },
      {
        name: "hackerrank",
        link: "https://www.hackerrank.com/rahulrj11?hr_r=1"
      }
    ],
    hobbies: ["sketch", "anime", "cricket", "travel", "beach", "chicken"]
  },
  details: {
    skills: {
      backend: [
        { name: "rails", experience: "2.5+" },
        { name: "ruby", experience: "2.5+" },
        { name: "python" }
      ],
      frontend: [
        { name: "react", experience: "2+" },
        { name: "redux", experience: "2+" },
        { name: "rails", experience: "2.5+" },
        { name: "javascript", experience: "2.5+" },
        { name: "antd", experience: "1.5+" }
      ],
      database: [
        { name: "psql", experience: "2.5+" },
        { name: "mongodb", experience: "0.5+" }
      ],
      tools: [
        { name: "git" },
        { name: "jira" },
        { name: "confluence" },
        { name: "ubuntu" }
      ]
    },
    experience: [
      {
        company: "BigBinary Solutions Pvt. Ltd, ​Pune",
        logo: "bigbinary",
        companyLink: "https://bigbinary.com/",
        designation: "Software Engineer",
        period: "FEB 2020 - PRESENT",
        description:
          "Involved in client interactions, designing, and developing end-to-end features. Working on a small-scale system in the health domain to create a referral network for caregivers and patients.",
        responsibilities: [
          "Designing and Writing RESTful Apis.",
          "Writing testable code by understanding system requirements.",
        ],
        technologies: "rails, ruby, react, psql"
      },
      {
        company: "Josh software Pvt. Ltd, ​Pune",
        logo: "josh",
        companyLink: "https://joshsoftware.com",
        designation: "Software Engineer",
        period: "JUN 2018 - OCT 2020",
        description:
          "Involved in designing, and developing end-to-end features. Worked on the systems in the media domain to build the digital platform for the ad-sales business.",
        responsibilities: [
          "Designing and Writing RESTful Apis.",
          "Writing optimized and testable code by understanding system requirements.",
          "Extensive POC of features and solutions for the business requirements.",
          "Building UI components and backend integration.",
          "Identifying bottlenecks across the system and optimize database queries, page load time, background job processing, caching.",
        ],
        technologies: "rails, ruby, react, redux, psql, jira"
      },
      {
        company: "Josh software Pvt. Ltd, ​Pune",
        logo: "josh",
        companyLink: "https://joshsoftware.com",
        designation: "​Intern",
        period: "JAN 2018 - MAY 2018",
        description:
          "Worked on an open source project based on ruby on rails platform. Open source project to motivate and reward open source contributors based on quality of commits and activities.",
        responsibilities: [
          "Designing and Writing RESTful Apis.",
          "Writing optimized and testable code by understanding system requirements.",
          "Building UI components as per the requirements.",
          "Coming up with new ideas/features to get the attention of end users"
        ],
        technologies: "rails, ruby, javascript, jquery, haml, mongodb"
      }
    ],
    projects: [
      {
        title: "MedigapLife - Referral - Current Project",
        sub_title: "FEB 2020 - PRESENT",
        description:
          "The project is focused on creating an online referral network for caregivers and patients. The system tracks referrals and earnings generated by each caregiver along with few auxiliary services.",
        technologies: "rails, ruby, react, psql"
      },
      {
        title: "MINT - Sports - Last Project",
        sub_title: "JUL 2019 - OCT 2020",
        description:
          "The project is focused on sales and prs team of star sports to handle their ad-sales business for sport channels. It helps them to move from manual to automated processing. It also helps stakeholders to get the entire visibility of their available and booked inventory in various views. It sets specific workflow for the sales-advertisement department.",
        technologies: "rails, ruby, react, redux, psql, jira"
      },
      {
        title: "MINT - Entertainment",
        sub_title: "JUL 2018 - JUN 2019",
        description:
          "The project is focused on the sales team of star tv to handle their ad-sales business for entertainment channels. It helps them to move from manual to automated processing. It also helps stakeholders to get the entire visibility of their inventory by products. Idea is same as the MINT-sports project but in different areas.",
        technologies: "rails, ruby, react, redux, psql, jira"
      },
      {
        title: "Code-curiosity - Internship project",
        sub_title: "JAN 2018 - JUN 2018",
        description:
          "Open source project to motivate and reward open source contributors based on quality of commits and activities. Using github apis to get required data of user's commits and activities, applying a scoring algorithm on them to give users a motivational reward.",
        technologies: "rails, ruby, javascript, jquery, haml, mongodb"
      },
      {
        title: "Image processing usign Hadoop",
        sub_title: "OCT 2017 - MAR 2018",
        description:
          "Project to process and analyse big data (images) using Hadoop. Creating sets of images and comparing them on single-node and multi-node clusters. Processing image data like iris and fingerprint patterns in distributed manner and comparing sequential results with distributed results.",
        responsibilities: "",
        technologies: "hadoop, java"
      },
      {
        title: "Jaya algorithm",
        sub_title: "AUG 2017 – NOV 2017",
        description:
          "Jaya algorithm is population based heuristic algorithm. It is a algorithm-specific parameter-less optimisation algorithm which has many useful applications in research field. I implemented this algorithm in python.",
        technologies: "python"
      },
      {
        title: "Minutes of Meetings",
        sub_title: "JAN 2017 – APR 2017",
        description:
          "It is web based project. It is a platform to take online meetings and keep each meeting's record in user friendly manner. In this admin can create meeting, take attendance of attendees, assign tasks to members, make timeline for each task, maintain online submissions of tasks.",
        technologies: "java, javascript, mysql"
      },
      {
        title: "Blender Animation",
        sub_title: "AUG 2016 – NOV 2016",
        description:
          "Blender animation of TLBO algorithm. It is a animated way of explaining and easy to understand a difficult algorithm.",
        technologies: "blender"
      }
    ],
    education: [
      {
        institute: "Walchand College Of Engineering, Sangli",
        degreeAbbreviation: "B.Tech",
        degree: "Bachelor of Technology in Information Technology",
        period: "JUL 2014 - MAY 2018",
        marks: "CPI - 8.1"
      },
      {
        institute: "Maharashtra Junior College, ​Latur",
        degreeAbbreviation: "HSC",
        degree: "Higher Secondary Certificate",
        period: "JUL 2012 - MAY 2014",
        marks: "Percentage - 76.15%"
      },
      {
        institute: "Jawahar Navodaya Vidyalaya, ​Latur",
        degreeAbbreviation: "SSC",
        degree: "Secondary School Certificate",
        period: "JUL 2011 - MAY 2012",
        marks: "CGPA - 9.4"
      }
    ]
  }
};
